import { type Item } from '@/lib/types'

export const genres: Item[] = [
    { id: 1, genre: 'Adventure', emoji: '🧭' },
    { id: 2, genre: 'Sci-fi', emoji: '👽' },
    { id: 3, genre: 'Comedy', emoji: '😂' },
    { id: 4, genre: 'Fantasy', emoji: '🧙‍♂️' },
    { id: 5, genre: 'Mystery', emoji: '🔍' },
    { id: 6, genre: 'Mythology', emoji: '🐉' },
    { id: 7, genre: 'Drama', emoji: '🎭' },
    { id: 8, genre: 'Action', emoji: '💥' },
    { id: 9, genre: 'Horror', emoji: '👻' },
    { id: 10, genre: 'Musical', emoji: '🎵' },
    { id: 11, genre: 'History', emoji: '🏛️' },
    { id: 12, genre: 'Crime', emoji: '🕵️‍♂️' },
    { id: 13, genre: 'Science', emoji: '🔬' },
    { id: 14, genre: 'Technology', emoji: '📱' },
    { id: 15, genre: 'Health', emoji: '🏥' },
    { id: 16, genre: 'Sports', emoji: '🏀' },
    { id: 17, genre: 'Cooking', emoji: '🍳' },
    { id: 18, genre: 'Art', emoji: '🎨' },
]

export const themes: Item[] = [
    { id: 1, theme: 'Futuristic city', emoji: '🌆' },
    { id: 2, theme: 'Ancient city', emoji: '🏛️' },
    { id: 3, theme: 'Medieval castle', emoji: '🏰' },
    { id: 4, theme: 'Jungle', emoji: '🌴' },
    { id: 5, theme: 'Beach', emoji: '🏖️' },
    { id: 6, theme: 'Mountain', emoji: '🏔️' },
    { id: 7, theme: 'Outer space', emoji: '🚀' },
    { id: 8, theme: 'Underground city', emoji: '🕳️' },
    { id: 9, theme: 'Desert island', emoji: '🏝️' },
    { id: 10, theme: 'Dcientific laboratory', emoji: '🔬' },
    { id: 11, theme: 'Parallel dimension', emoji: '🌀' },
    { id: 12, theme: 'Floating city', emoji: '🏙️' },
    { id: 13, theme: 'Alien planet', emoji: '👽' },
    { id: 14, theme: 'Time capsule in the past', emoji: '⏳' },
    { id: 15, theme: 'Space station', emoji: '🛰️' },
    { id: 16, theme: 'Post-apocalyptic desert', emoji: '☢️' },
    { id: 17, theme: 'Submarine base', emoji: '🌊' },
    { id: 18, theme: 'Magic village', emoji: '🧙‍♂️' },
    { id: 19, theme: 'Neon jungle', emoji: '🌃' },
    { id: 20, theme: 'Village in the clouds', emoji: '☁️' },
    { id: 21, theme: 'Ancient temple in the mountain', emoji: '🏞️' },
    { id: 22, theme: 'Farm in space', emoji: '🚜' },
    { id: 23, theme: 'City of machines', emoji: '🤖' },
    { id: 24, theme: 'Ruins of an ancient civilization at the bottom of the sea', emoji: '🌊' },
    { id: 25, theme: 'Extreme sports orbital platform', emoji: '🛸' },
    { id: 26, theme: 'Magic school on a floating island', emoji: '🏝️' },
    { id: 27, theme: 'City submerged in perpetual rain', emoji: '🌧️' },
    { id: 28, theme: 'Enchanted forest', emoji: '🌲' },
    { id: 29, theme: 'City in the clouds', emoji: '☁️' },
    { id: 30, theme: 'Colonized moon', emoji: '🌕' },
    { id: 31, theme: 'Base at the South Pole', emoji: '🏔️' },
    { id: 32, theme: 'Ice city', emoji: '❄️' },
    { id: 33, theme: 'Mysterious circus', emoji: '🎪' },
    { id: 34, theme: 'Ghost ship in the fog', emoji: '👻' },
    { id: 35, theme: 'Dream factory', emoji: '💭' },
    { id: 36, theme: 'City in the cave', emoji: '🕳️' },
    { id: 38, theme: 'Train station in space', emoji: '🚂' },
    { id: 39, theme: 'Asteroid field', emoji: '☄️' },
    { id: 40, theme: 'Haunted house on the hill', emoji: '🏚️' },
    { id: 41, theme: 'Village at the bottom of a lunar crater', emoji: '🌑' },
    { id: 42, theme: 'Glass city', emoji: '💎' },
    { id: 45, theme: 'Colony on Mars', emoji: '🪐' },
    { id: 48, theme: 'Time room', emoji: '⏳' },
    { id: 49, theme: 'Shelter in the center of the Earth', emoji: '🌍' },
    { id: 50, theme: 'Ruined city on an asteroid', emoji: '☄️' },
    { id: 51, theme: 'Abandoned amusement park on the Moon', emoji: '🌕' },
    { id: 52, theme: 'Steampunk era village', emoji: '🔧' },
    { id: 55, theme: 'Puppet city', emoji: '🎭' },
    { id: 57, theme: 'Camp in eternal snow', emoji: '❄️' },
    { id: 58, theme: 'City in the mouth of a sleeping giant', emoji: '😴' },
    { id: 59, theme: 'Floating island of butterflies', emoji: '🦋' },
    { id: 60, theme: 'Artificial intelligence laboratory', emoji: '🤖' },
    { id: 61, theme: 'Forest of talking trees', emoji: '🌳' },
    { id: 62, theme: 'City in a wormhole', emoji: '🌀' },
    { id: 63, theme: 'Holographic village', emoji: '🌈' },
    { id: 64, theme: 'Base on the side of an alien cliff', emoji: '👽' },
    { id: 65, theme: 'Land of giants', emoji: '👣' },
    { id: 66, theme: 'Lunar landscape of mirages', emoji: '🌕' },
    { id: 67, theme: 'City inside a giant diamond', emoji: '💎' },
    { id: 68, theme: 'Desert of liquid glass', emoji: '💧' },
    { id: 69, theme: 'Colony on a wandering asteroid', emoji: '☄️' },
    { id: 70, theme: 'Sanctuary in the center of a labyrinth', emoji: '🌀' },
    { id: 71, theme: 'City of floating spheres', emoji: '🔮' },
    { id: 72, theme: 'Village on the bank of a lava river', emoji: '🌋' },
    { id: 73, theme: 'City on the back of a gigantic mechanized creature', emoji: '🦕' },
    { id: 75, theme: 'Ghost ship trapped in an eternal storm', emoji: '🌪️' },
    { id: 76, theme: 'Secret laboratory in the center of the Earth', emoji: '🌍' },
    { id: 77, theme: 'Village in a desert where gems rain', emoji: '💎' },
    { id: 78, theme: 'Magical library with books that come to life', emoji: '📚' },
    { id: 79, theme: 'Abandoned amusement park on the Moon', emoji: '🌕' },
    { id: 80, theme: 'Floating garden in space', emoji: '🌌' },
    { id: 81, theme: 'Island inhabited by mythological beings', emoji: '🐉' },
    { id: 82, theme: 'City where everyone has wings', emoji: '🦋' },
    { id: 83, theme: 'Temporal zone where different epochs converge', emoji: '⏳' },
    { id: 84, theme: 'Castle in a cloud', emoji: '☁️' },
    { id: 85, theme: 'Cave with portals to other worlds', emoji: '🌀' },
    { id: 86, theme: 'Jungle where plants have magical powers', emoji: '🌿' },
    { id: 87, theme: 'Prison in an alternate dimension', emoji: '🔒' },
    { id: 88, theme: 'City where gravity works in reverse', emoji: '🔄' },
    { id: 89, theme: 'Village where the night lasts a minute', emoji: '🌙' },
    { id: 90, theme: 'Planet inhabited by artificial intelligences', emoji: '🤖' },
    { id: 91, theme: 'Theater where the actors are holograms', emoji: '🎭' },
    { id: 92, theme: 'Lake that grants wishes at sunset', emoji: '🌅' },
    { id: 93, theme: 'Space station with floating gardens', emoji: '🌌' },
    { id: 94, theme: 'Mountains that whisper secrets to the wind', emoji: '🏔️' },
    { id: 95, theme: 'City where all buildings are living beings', emoji: '🏢' },
    { id: 97, theme: 'Place where memories take physical form', emoji: '🧠' },
    { id: 98, theme: 'Island of the changing mirages', emoji: '🏝️' },
    { id: 99, theme: 'Ruins of a civilization inside a volcano', emoji: '🌋' },
    { id: 100, theme: 'Alley that connects different dimensions', emoji: '🌀' },
    { id: 101, theme: 'Forest where shadows come to life', emoji: '🌲' },
    { id: 102, theme: 'City under the influence of a silence spell', emoji: '🔇' },
    { id: 103, theme: 'Waterfall that flows backwards', emoji: '🔄' },
    { id: 105, theme: 'Beach where the waves sing forgotten songs', emoji: '🌊' },
    { id: 106, theme: 'Academy for interdimensional beings', emoji: '📚' },
    { id: 107, theme: 'City suspended in time', emoji: '⏳' },
    { id: 108, theme: 'Lake with water that cures any disease', emoji: '🌊' },
    { id: 110, theme: 'City where day and night are interchangeable', emoji: '🔄' },
    { id: 111, theme: 'Valley of optical illusions', emoji: '🌄' },
    { id: 112, theme: 'Island where seasons change every hour', emoji: '🌞' },
    { id: 113, theme: 'Labyrinth of infinite dreams', emoji: '💭' },
    { id: 114, theme: 'Cavern with crystals that show visions of the future', emoji: '🔮' },
    { id: 115, theme: 'Floating city in the atmosphere of a gas giant', emoji: '🌌' },
    { id: 116, theme: 'Square where statues come to life during the full moon', emoji: '🌕' },
    { id: 117, theme: 'Forest where shadows dance to the rhythm of the wind', emoji: '🌲' },
    { id: 118, theme: 'Highlands where the sun never sets', emoji: '🌞' },
    { id: 119, theme: 'City built on the shell of a gigantic creature', emoji: '🐢' },
    { id: 120, theme: 'Market where emotions are exchanged in jars', emoji: '🧴' },
    { id: 125, theme: 'Glass jungle with bioluminescent animals', emoji: '🌿' },
    { id: 126, theme: 'Scientific base on a inhospitable planet', emoji: '🪐' },
    { id: 127, theme: 'Ghost ship in the Bermuda Triangle', emoji: '👻' },
    { id: 128, theme: 'Floating city in the clouds', emoji: '☁️' },
    { id: 129, theme: 'Magical library with books that come to life', emoji: '📚' },
    { id: 130, theme: 'Train that travels through time', emoji: '🚂' },
    { id: 131, theme: 'Garden of flowers that only bloom at night', emoji: '🌙' },
    { id: 132, theme: 'Desert island inhabited by robots', emoji: '🤖' },
    { id: 133, theme: 'Enchanted forest with trees that whisper secrets', emoji: '🌲' },
    { id: 134, theme: 'Underground laboratory of genetic experiments', emoji: '🧬' },
    { id: 135, theme: 'Village of tiny creatures in the forest', emoji: '🌳' },
    { id: 136, theme: 'Alien market on an asteroid', emoji: '☄️' },
    { id: 137, theme: 'Prison in an alternate dimension', emoji: '🔒' },
    { id: 138, theme: 'Floating mountains on a distant planet', emoji: '🪐' },
    { id: 139, theme: 'Ruins of an extraterrestrial civilization', emoji: '👽' },
    { id: 140, theme: 'Shadow theater with invisible actors', emoji: '👤' },
    { id: 141, theme: 'Abandoned amusement park in space', emoji: '🛸' },
    { id: 142, theme: 'City where people can fly', emoji: '🦸‍♂️' },
    { id: 143, theme: 'Cave with crystals that emit music', emoji: '🎵' },
    { id: 144, theme: 'Town inhabited by fire beings', emoji: '🔥' },
    { id: 145, theme: 'Lava lake with floating metal islands', emoji: '🌋' },
    { id: 146, theme: 'Haunted house in a dark forest', emoji: '👻' },
    { id: 147, theme: 'Spy academy on a snowy mountain', emoji: '🏔️' },
    { id: 148, theme: 'Underwater cave with fish that glow in the dark', emoji: '🐠' },
    { id: 149, theme: 'Dream market in the dream world', emoji: '💭' },
    { id: 150, theme: 'City where all buildings are living beings', emoji: '🏢' },
    { id: 151, theme: 'Dimensional tunnel leading to different realities', emoji: '🌀' },
    { id: 152, theme: 'Beach where the waves are colorful', emoji: '🌈' },
    { id: 153, theme: 'Waterfall that flows upwards', emoji: '🔄' },
    { id: 154, theme: 'Amusement park on the Moon', emoji: '🌕' },
    { id: 155, theme: 'Magical alley with shops that sell wishes', emoji: '🧞' },
    { id: 156, theme: 'Volcanic island inhabited by friendly dragons', emoji: '🐉' },
    { id: 157, theme: 'Bar at the end of the universe', emoji: '🌌' },
    { id: 158, theme: 'City under the ice on a frozen planet', emoji: '❄️' },
    { id: 159, theme: 'Alchemy laboratory in an enchanted forest', emoji: '🌲' },
    { id: 160, theme: 'Virtual reality game with infinite worlds', emoji: '🎮' },
    { id: 161, theme: 'Spaceship graveyard on an asteroid', emoji: '☄️' },
    { id: 162, theme: 'Village where everyone is an artist', emoji: '🎨' },
    { id: 163, theme: 'Forest of mirrors with talking reflections', emoji: '🌲' },
    { id: 164, theme: 'Magic stone that grants a wish per century', emoji: '💎' },
    { id: 165, theme: 'Castle in a cloud inhabited by ethereal beings', emoji: '☁️' },
    { id: 166, theme: 'Quarantine zone for paranormal phenomena', emoji: '👻' },
    { id: 167, theme: 'Island inhabited by mythological creatures', emoji: '🐉' },
    { id: 168, theme: 'City where it rains candies', emoji: '🍬' },
    { id: 169, theme: 'Temple at the top of an inaccessible mountain', emoji: '🏔️' },
    { id: 170, theme: 'Underwater park with living sculptures', emoji: '🐠' },
    { id: 171, theme: 'Flying school for winged creatures', emoji: '🦋' },
    { id: 172, theme: 'Dream factory in a cloud', emoji: '💭' },
    { id: 173, theme: 'Forest of singing trees', emoji: '🌲' },
    { id: 174, theme: 'Prison of the mind where thoughts are imprisoned', emoji: '🧠' },
    { id: 175, theme: 'Cave with water that cures any disease', emoji: '🌊' },
    { id: 176, theme: 'City where each building is a giant puzzle', emoji: '🧩' },
    { id: 177, theme: 'Bridge that connects two dimensions', emoji: '🌀' },
    { id: 178, theme: 'Planet with reverse gravity', emoji: '🔄' },
    { id: 179, theme: 'Space station inhabited by light beings', emoji: '🌌' },
    { id: 180, theme: 'Floating island where animals talk', emoji: '🏝️' },
    { id: 181, theme: 'Puppet theater with living puppets', emoji: '🎭' },
    { id: 182, theme: 'Jungle of plants that move by their own will', emoji: '🌿' },
    { id: 183, theme: 'Underground city illuminated by bioluminescent crystals', emoji: '🔮' },
    { id: 184, theme: 'Library of dreams with books that reveal possible futures', emoji: '💭' },
    { id: 185, theme: 'Clock tower that controls time in a magical kingdom', emoji: '⏳' },
    { id: 186, theme: 'Water park on a planet with colored water', emoji: '🌈' },
    { id: 188, theme: 'City where buildings are mechanical giants', emoji: '🏢' },
    { id: 189, theme: 'Cave of crystals that emit healing energy', emoji: '💎' },
    { id: 191, theme: 'Flying island inhabited by invisible beings', emoji: '👤' },
    { id: 192, theme: 'Scientific base in the center of the Earth', emoji: '🌍' },
    { id: 193, theme: 'Secret garden where plants with magical properties grow', emoji: '🌿' },
    { id: 194, theme: 'Village where gravity is variable', emoji: '🔄' },
    { id: 195, theme: 'City inside a giant bubble', emoji: '🔮' },
    { id: 196, theme: 'Underwater cave with paintings that come to life', emoji: '🎨' },
    { id: 197, theme: 'Market of magical artifacts in an underground city', emoji: '🔮' },
    { id: 198, theme: 'Beach of golden sand on a distant planet', emoji: '🪐' },
    { id: 200, theme: 'Ruins of an alien civilization on the Moon', emoji: '🌕' },
]

export const characters: Item[] = [
    { id: 1, character: 'Fairy', emoji: '🧚‍♀️' },
    { id: 2, character: 'Vampire', emoji: '🧛' },
    { id: 3, character: 'Mermaid', emoji: '🧜' },
    { id: 4, character: 'King', emoji: '👑' },
    { id: 5, character: 'Pirate', emoji: '☠️' },
    { id: 6, character: 'Witch', emoji: '🧙‍♀️' },
    { id: 7, character: 'Explorer', emoji: '🌍' },
    { id: 8, character: 'Hunter', emoji: '🏹' },
    { id: 9, character: 'Robot', emoji: '🤖' },
    { id: 10, character: 'Princess', emoji: '👸' },
    { id: 11, character: 'Astronaut', emoji: '👨‍🚀' },
    { id: 12, character: 'Ghost', emoji: '👻' },
    { id: 13, character: 'Dragon', emoji: '🐉' },
    { id: 14, character: 'Pilot', emoji: '👨‍✈️' },
    { id: 15, character: 'Ninja', emoji: '🉐' },
    { id: 16, character: 'Superhero', emoji: '🦸‍♂️' },
    { id: 17, character: 'Prince', emoji: '🤴' },
    { id: 18, character: 'Scientist', emoji: '🔬' },
    { id: 19, character: 'Wizard', emoji: '🎩' },
    { id: 20, character: 'Police', emoji: '👮‍♂️' },
    { id: 21, character: 'Viking', emoji: '⚔️' },
    { id: 22, character: 'Super Villain', emoji: '🦹‍♂️' },
    { id: 23, character: 'Dinosaur', emoji: '🦖' },
    { id: 24, character: 'Treasure Hunter', emoji: '💰' },
    { id: 25, character: 'Navigator', emoji: '🗺️' },
    { id: 26, character: 'Scientist', emoji: '👩‍🔬' },
    { id: 27, character: 'Doctor', emoji: '👨‍⚕️' },
    { id: 28, character: 'Dancer', emoji: '💃' },
    { id: 29, character: 'Chef', emoji: '👨‍🍳' },
    { id: 30, character: 'Alien', emoji: '👽' },
    { id: 31, character: 'Musician', emoji: '🎵' },
    { id: 32, character: 'Archaeologist', emoji: '🦴' },
    { id: 33, character: 'Painter', emoji: '👨‍🎨' },
    { id: 34, character: 'Astronomer', emoji: '🔭' },
    { id: 35, character: 'Firefighter', emoji: '👨‍🚒' },
    { id: 36, character: 'Knight', emoji: '🛡️' },
    { id: 37, character: 'Helicopter Pilot', emoji: '🚁' },
    { id: 38, character: 'Cowboy', emoji: '🤠' },
    { id: 39, character: 'Surgeon', emoji: '👨‍⚕️' },
    { id: 40, character: 'Diver', emoji: '🤿' },
    { id: 41, character: 'Teacher', emoji: '👨‍🏫' },
    { id: 42, character: 'Librarian', emoji: '📚' },
    { id: 43, character: 'Architect', emoji: '🏛️' },
    { id: 44, character: 'Hacker', emoji: '👨‍💻' },
    { id: 45, character: 'Cook', emoji: '👨‍🍳' },
    { id: 46, character: 'Boxer', emoji: '🥊' },
    { id: 47, character: 'Fisherman', emoji: '🎣' },
    { id: 48, character: 'Samurai', emoji: '👹' },
    { id: 49, character: 'Monster Hunter', emoji: '👾' },
    { id: 50, character: 'Clown', emoji: '🤡' },
    { id: 51, character: 'Dentist', emoji: '🦷' },
    { id: 52, character: 'Sculptor', emoji: '🗿' },
    { id: 53, character: 'Reporter', emoji: '🎥' },
    { id: 54, character: 'Train Driver', emoji: '🚂' },
    { id: 55, character: 'Golfer', emoji: '🏌️' },
    { id: 56, character: 'Veterinarian', emoji: '🐾' },
    { id: 57, character: 'Singer', emoji: '🎤' },
    { id: 58, character: 'Magic Genie', emoji: '🧞' },
    { id: 59, character: 'Football Coach', emoji: '⚽' },
    { id: 60, character: 'Photographer', emoji: '📸' },
    { id: 61, character: 'Elf', emoji: '🧝‍♂️' },
    { id: 62, character: 'Traffic Police', emoji: '🚦' },
    { id: 63, character: 'Sushi Chef', emoji: '🍣' },
    { id: 64, character: 'Film Director', emoji: '🎬' },
    { id: 65, character: 'Elf', emoji: '🧝‍♀️' },
    { id: 66, character: 'Parachutist', emoji: '🪂' },
    { id: 67, character: 'Orchestra Conductor', emoji: '🎶' },
    { id: 68, character: 'Shoemaker', emoji: '👞' },
    { id: 69, character: 'Gardener', emoji: '🌻' },
    { id: 70, character: 'Fencer', emoji: '🤺' },
    { id: 71, character: 'Juggler', emoji: '🤹‍♂️' },
    { id: 72, character: 'Horse Rider', emoji: '🏇' },
    { id: 73, character: 'Pilot', emoji: '✈️' },
    { id: 74, character: 'Firefighter', emoji: '🚒' },
    { id: 75, character: 'Barista', emoji: '☕' },
    { id: 76, character: 'Football Player', emoji: '⚽' },
    { id: 77, character: 'Space Scientist', emoji: '🚀' },
    { id: 78, character: 'Writer', emoji: '📝' },
    { id: 79, character: 'Detective', emoji: '🕵️‍♂️' },
    { id: 80, character: 'Waiter', emoji: '🍽️' },
    { id: 81, character: 'Electrician', emoji: '⚡' },
    { id: 82, character: 'Surfer', emoji: '🏄' },
    { id: 83, character: 'Court Judge', emoji: '⚖️' },
    { id: 84, character: 'Cyclist', emoji: '🚴' },
    { id: 85, character: 'Farmer', emoji: '👩‍🌾' },
    { id: 86, character: 'Zombie', emoji: '🧟‍♀️' },
    { id: 87, character: 'Archer', emoji: '🏹' },
    { id: 88, character: 'Circus Artist', emoji: '🤹‍♀️' },
    { id: 89, character: 'Ballet Dancer', emoji: '🩰' },
    { id: 90, character: 'Mechanic', emoji: '👨‍🔧' },
    { id: 91, character: 'Journalist', emoji: '📰' },
    { id: 92, character: 'Guard', emoji: '👮‍♂️' },
    { id: 93, character: 'Chess Player', emoji: '♟️' },
];

export const specialFeatures: Item[] = [
    { id: 1, feature: 'time travel', emoji: '⏳' },
    { id: 2, feature: 'flight', emoji: '🦸‍♂️' },
    { id: 3, feature: 'teleportation', emoji: '🌀' },
    { id: 4, feature: 'super strength', emoji: '💪' },
    { id: 6, feature: 'fire control', emoji: '🔥' },
    { id: 7, feature: 'water control', emoji: '🌊' },
    { id: 8, feature: 'earth control', emoji: '🌍' },
    { id: 9, feature: 'air control', emoji: '💨' },
    { id: 10, feature: 'electricity control', emoji: '⚡' },
    { id: 11, feature: 'plant control', emoji: '🌿' },
    { id: 12, feature: 'mind control', emoji: '🧠' },
    { id: 13, feature: 'telepathy', emoji: '🔮' },
    { id: 14, feature: 'telekinesis', emoji: '🌀' },
    { id: 15, feature: 'animal communication', emoji: '🐾' },
    { id: 23, feature: 'future sight', emoji: '🔮' },
    { id: 24, feature: 'past sight', emoji: '🔮' },
    { id: 25, feature: 'dimensional sight', emoji: '🌀' },
    { id: 32, feature: 'ghost sight', emoji: '👻' },
    { id: 33, feature: 'shape shifting', emoji: '🦄' },
    { id: 34, feature: 'immortality', emoji: '🧛‍♂️' },
    { id: 35, feature: 'invisibility', emoji: '👤' },
    { id: 36, feature: 'size changing', emoji: '🔍' },
    { id: 37, feature: 'gravity control', emoji: '🔄' },
    { id: 38, feature: 'time control', emoji: '⏳' },
    { id: 39, feature: 'super speed', emoji: '🏃‍♂️' },
    { id: 40, feature: 'rainbow creation', emoji: '🌈' },
    { id: 41, feature: 'illusion creation', emoji: '🔮' },
    { id: 42, feature: 'demon summoning', emoji: '👹' },
    { id: 43, feature: 'angel summoning', emoji: '👼' },
    { id: 44, feature: 'magic mastery', emoji: '🧙‍♂️' },
    { id: 45, feature: 'poison mastery', emoji: '🐍' },
    { id: 46, feature: 'light mastery', emoji: '💡' },
    { id: 47, feature: 'darkness mastery', emoji: '🌑' },
    { id: 48, feature: 'ice mastery', emoji: '❄️' },
    { id: 50, feature: 'sound mastery', emoji: '🔊' },
    { id: 51, feature: 'music mastery', emoji: '🎵' },
    { id: 52, feature: 'dance mastery', emoji: '💃' },
    { id: 53, feature: 'painting mastery', emoji: '🎨' }
]


export const ignoredWords = new Set(['he', 'she', 'it', 'they', 'them', 'and', 'or', 'a', 'an', 'of', 'the', 'to', 'with', 'in', 'on', 'his', 'her', 'its', 'by', 'for', 'from', 'at', 'is', 'this', 'that', 'those', 'these', 'once', 'had', 'whose', 'who', 'which', 'but', 'until', 'more', 'less', 'yes', 'no', 'nor', 'also', 'about', 'between', 'after', 'when', 'where', 'because', 'so', 'all', 'every', 'since', 'then', 'had', 'many', 'few', 'same', 'towards', 'each', 'any', 'anyone', 'anyone', '─','-']);
